### ISSUE TITLE
JAXB exception appear when running topology standard and cluster

### ISSUE THREAD

**Issue by lgrateau** [ODMDev/odm-ondocker#173]
When running the topology standard / clustered this exception is raised. 

com.ibm.rules.res.xml.internal.JAXBContext.newInstance(JAXBContext.java:98)
odm-decisionserverconsole_1  |     at com.ibm.rules.res.model.rest.binding.internal.RESTServiceBindingBase.<init>(RESTServiceBindingBase.java:45)
odm-decisionserverconsole_1  |     ... 31 more
odm-decisionserverconsole_1  | Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory
odm-decisionserverconsole_1  |     at java.lang.Class.forNameImpl(Native Method)
odm-decisionserverconsole_1  |     at java.lang.Class.forName(Class.java:332)
odm-decisionserverconsole_1  |     at com.ibm.rules.res.xml.internal.JAXBContext.newInstance(JAXBContext.java:81)
odm-decisionserverconsole_1  |     ... 32 more
odm-decisionserverconsole_1  |

**Comment by lgrateau** [comment]
This is register as a defect in the Docker webpshere Liberty 18.0.0.2.
https://github.com/OpenLiberty/open-liberty/issues/4404
and
https://github.com/OpenLiberty/open-liberty/issues/5056

We are waiting the delivery of the next Websphere Liberty 18.0.0.3 docker image that will fixed the pb.

**Comment by lgrateau** [comment]
The liberty docker 18.0.0.3 is available in docker hub. This should fix the pb
