### ISSUE TITLE
Connection failed for the Decision Runner when running a test suite from Decision Center

### ISSUE THREAD

**Issue by rachel-orti** [ODMDev/odm-ondocker#36]
decisioncenter_1         | [WARNING ] [Report - 2017-08-21_03-32-29-645] nullilog.rules.teamserver.model.IlrTestingException: http://localhost:9070/DecisionRunner is not a valid Decision Runner URL. CDIHttpClient cannot be created.
decisioncenter_1         | Connect to localhost:9070 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
decisioncenter_1         | Connection refused (Connection refused)
decisioncenter_1         | 	at ilog.rules.teamserver.ejb.service.validation.IlrTestSuiteService.createDecisionRunnerClient(IlrTestSuiteService.java:557)
decisioncenter_1         | 	at ilog.rules.teamserver.ejb.service.validation.IlrTestSuiteService.asynchronousPrepare(IlrTestSuiteService.java:213)
decisioncenter_1         | 	at ilog.rules.teamserver.ejb.service.validation.PrepareArchiveThreadService.run(PrepareArchiveThreadService.java:57)
decisioncenter_1         | 	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
decisioncenter_1         | 	at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
decisioncenter_1         | 	at java.lang.Thread.run(Thread.java:785)
decisioncenter_1         | Caused by: java.lang.IllegalArgumentException: http://localhost:9070/DecisionRunner is not a valid Decision Runner URL. CDIHttpClient cannot be created.
decisioncenter_1         | 	at com.ibm.rules.cdi.client.CDIClientServiceFactory.createHTTPClient(CDIClientServiceFactory.java:125)
decisioncenter_1         | 	at com.ibm.rules.cdi.client.CDIClientServiceFactory.createHTTPClient(CDIClientServiceFactory.java:103)
decisioncenter_1         | 	at ilog.rules.teamserver.model.validation.ValidationHelper.createDecisionRunnerClient(ValidationHelper.java:75)
decisioncenter_1         | 	at ilog.rules.teamserver.ejb.service.validation.IlrTestSuiteService.createDecisionRunnerClient(IlrTestSuiteService.java:555)
decisioncenter_1         | 	... 5 more
decisioncenter_1         | Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:9070 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
decisioncenter_1         | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
decisioncenter_1         | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
decisioncenter_1         | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
decisioncenter_1         | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
decisioncenter_1         | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
decisioncenter_1         | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
decisioncenter_1         | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
decisioncenter_1         | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
decisioncenter_1         | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
decisioncenter_1         | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
decisioncenter_1         | 	at com.ibm.rules.cdi.client.CDIClientServiceFactory.isDecisionRunner(CDIClientServiceFactory.java:147)
decisioncenter_1         | 	at com.ibm.rules.cdi.client.CDIClientServiceFactory.createHTTPClient(CDIClientServiceFactory.java:121)
decisioncenter_1         | 	... 8 more
decisioncenter_1         | Caused by: java.net.ConnectException: Connection refused (Connection refused)
decisioncenter_1         | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:380)
decisioncenter_1         | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:236)
decisioncenter_1         | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:218)
decisioncenter_1         | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
decisioncenter_1         | 	at java.net.Socket.connect(Socket.java:666)
decisioncenter_1         | 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
decisioncenter_1         | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
decisioncenter_1         | 	... 19 more
decisioncenter_1         |

**Comment by rachel-orti** [comment]
Issue #26 fixes #36.
