### ISSUE TITLE
Intermittent NoHttpResponseException when creating and running a test suite by API

### ISSUE THREAD

**Issue by rachel-orti** [ODMDev/odm-ondocker#47]
Reproduced intermittently with the standard and standalone topologies on dev so far. 

org.springframework.remoting.RemoteAccessException: Could not access HTTP invoker remote service at [http://**xxxx**:9060/decisioncenter/remoting/session?__dcsid=2ed102755c6b758f07f2f12037e0f97c]; nested exception is org.apache.http.NoHttpResponseException: **xxxx**:9060 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.springframework.remoting.httpinvoker.HttpComponentsHttpInvokerRequestExecutor.executeHttpPost(HttpComponentsHttpInvokerRequestExecutor.java:354)
	at org.springframework.remoting.httpinvoker.HttpComponentsHttpInvokerRequestExecutor.doExecuteRequest(HttpComponentsHttpInvokerRequestExecutor.java:245)
	at org.springframework.remoting.httpinvoker.AbstractHttpInvokerRequestExecutor.executeRequest(AbstractHttpInvokerRequestExecutor.java:136)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:202)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.executeRequest(HttpInvokerClientInterceptor.java:184)
	at org.springframework.remoting.httpinvoker.HttpInvokerClientInterceptor.invoke(HttpInvokerClientInterceptor.java:150)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy10.getElementDetailsForThisHandle(Unknown Source)
	at ilog.rules.teamserver.model.impl.IlrAbstractSession.getElementDetails(IlrAbstractSession.java:1050)
	at ilog.rules.teamserver.model.impl.IlrAbstractCachingSession.getElementDetails(IlrAbstractCachingSession.java:80)
	at ilog.rules.teamserver.model.impl.IlrAbstractSession.getElementDetails(IlrAbstractSession.java:1037)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at ilog.rules.teamserver.client.IlrSessionInvocationHandler.invoke(IlrSessionInvocationHandler.java:43)
	at com.sun.proxy.$Proxy11.getElementDetails(Unknown Source)
	at com.ibm.odm.cloud.mat.tests.remoteconnection.RemoteConnectionBase.createAndRunTestSuite(RemoteConnectionBase.java:415)
	at com.ibm.odm.cloud.mat.tests.remoteconnection.DecisionCenterTestSuiteTest.testCreateAndRunDecisionCenterTestSuite(DecisionCenterTestSuiteTest.java:27)

**Comment by mmouly** [comment]
Shilpa changed a little bit the test code so the issue must appear less frequently.
Will reopen it if it happen again.
